# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker loging
      env:
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}  
        DOCKER_USER: ${{ secrets.DOCKER_USER }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: docker build app
      run: |
        docker build -t test_travis:1.0.0 .
    - name : docker push
      run: |
        docker push chenyaron/github_testing/test_travis:1.0.0
        

